apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-otel-demo-cartservice
  labels:

    opentelemetry.io/name: my-otel-demo-cartservice
    app.kubernetes.io/instance: my-otel-demo
    app.kubernetes.io/component: cartservice
    app.kubernetes.io/name: my-otel-demo-cartservice
    app.kubernetes.io/version: "1.11.0"
    app.kubernetes.io/part-of: my-otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:

      opentelemetry.io/name: my-otel-demo-cartservice
  template:
    metadata:
      labels:

        opentelemetry.io/name: my-otel-demo-cartservice
        app.kubernetes.io/instance: my-otel-demo
        app.kubernetes.io/component: cartservice
        app.kubernetes.io/name: my-otel-demo-cartservice
    spec:
      serviceAccountName: my-otel-demo
      containers:
        - name: cartservice
          image: 'ghcr.io/open-telemetry/demo:latest-cartservice'
          imagePullPolicy: IfNotPresent
          ports:

          - containerPort: 8080
            name: service
          env:
          - name: OTEL_SERVICE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.labels['app.kubernetes.io/component']
          - name: OTEL_COLLECTOR_NAME
            value: 'my-otel-demo-otelcol'
          - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
            value: cumulative
          - name: CART_SERVICE_PORT
            value: "8080"
          - name: ASPNETCORE_URLS
            value: http://*:$(CART_SERVICE_PORT)
          - name: VALKEY_ADDR
            value: 'my-otel-demo-valkey:6379'
          - name: FLAGD_HOST
            value: 'my-otel-demo-flagd'
          - name: FLAGD_PORT
            value: "8013"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(OTEL_COLLECTOR_NAME):4317
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=$(OTEL_SERVICE_NAME),service.namespace=my-otel-demo,service.version=1.11.0
          resources:
            limits:
              memory: 160Mi
          volumeMounts:
      volumes:
      initContainers:
        - command:
          - sh
          - -c
          - until nc -z -v -w30 my-otel-demo-valkey 6379; do echo waiting
            for valkey; sleep 2; done;
          image: busybox:latest
          name: wait-for-valkey
